from .generate_ccomp_xcomp_question import generate_ccomp_xcomp_question
from .generate_nmod_question import generate_nmod_question
from .generate_nummod_question import generate_nummod_question
from .generate_obj_question import generate_obj_question
from .generate_subj_question import generate_subj_question
from .generate_tmod_question import generate_tmod_question
from .abstract_tree_lv1 import get_question_abstract_tree_lv1
